import pandas as pd
import os
import sys



# ==============================================================================
# 1. CONFIGURATION & METADATA LOADING
# ==============================================================================
configfile: "config.yaml"
# Load reference name from config
REF_NAME = config.get("ref_name", "ref")

# Regex breakdown:
# [^_]+ means "one or more characters that are NOT an underscore"
# .+     means "one or more of any character"
wildcard_constraints:
    sample_id = "[^.]+",  # Stop at the first dot
    run_id    = "[^.]+",  # Stop at the next dot
    ref_name  = "[^.]+"   # Stop at the dot before .bam


#ADD rules here
include: "workflow/rules/mapping.smk"
include: "workflow/rules/subsampling.smk"
#include: "workflow/rules/2_call_genotypes.smk"
#include: "workflow/rules/2_alt_call_genotypes_noTrans.smk" #no transitions genotype calling workflow


#Function to load metadata with robust handling of missing files and columns
def load_metadata(file_key, source_name):
    file_path = config.get(file_key)
    expected_cols = ['sample_id', 'run_id','fq1', 'fq2', 'library', 'platform']
    
    if not file_path or not os.path.exists(file_path):
        # Return a truly empty dataframe with no rows
        return pd.DataFrame(columns=expected_cols)
    
    sep = '\t' if file_path.endswith(('.tsv', '.txt')) else ','
    df = pd.read_csv(file_path, sep=sep)
    
    # Only keep rows that have a sample_id
    df = df.dropna(subset=['sample_id'])
    
    if 'fq2' not in df.columns:
        df['fq2'] = "unknown"
        
    df = df.fillna("unknown")
    df['source'] = source_name
    return df

# Load both (or neither)
modern_df = load_metadata("modern_csv", "modern")
hist_df = load_metadata("historical_csv", "historical")

# Combine datasets
samples_df = pd.concat([modern_df, hist_df], ignore_index=True)

# REMOVE "unknown" rows that were generated by empty files or missing columns
samples_df = samples_df[samples_df['sample_id'] != "unknown"]

# Safety Check: Now truly check if there is real data left
if samples_df.empty:
    print("\nERROR: No valid samples found. Please check your metadata files.\n")
    sys.exit(1)
# Safety Check: If both files are missing or empty, stop and warn the user.
if samples_df.empty:
    print("\nERROR: No samples found. Check 'modern_csv' and 'historical_csv' in config.yaml\n")
    sys.exit(1)

# List of all unique Sample IDs for expansion logic
SAMPLES = samples_df['sample_id'].unique()

#'DEBUg: Loaded metadata for the following samples:'
#print("--- DEBUG: METADATA LOADED ---")
#print(samples_df[['sample_id', 'run_id', 'source']])
#print(f"Total rows found: {len(samples_df)}")
#print("------------------------------")

# ==============================================================================
# 2. TARGET GENERATION (
# ==============================================================================
def get_final_targets(wildcards):
    targets = []
    for _, row in samples_df.drop_duplicates('sample_id').iterrows():
        sid = row['sample_id']
        src = row['source']
        
        # 1. Base Dedup BAM targets
        targets.append(f"results/mapping/{src}/stats/merged_dedup_merged/{sid}.{REF_NAME}.merged.dedup.merged.stats.txt")
        targets.append(f"results/mapping/{src}/{sid}.{REF_NAME}.merged.dedup.merged.bam")
        #depth file for dedup BAMs (Fixed to match the new output from mapping rules)
        targets.append(f"results/mapping/{src}/stats/merged_dedup_merged/{sid}.{REF_NAME}.merged.dedup.merged.regfilt.Q20.q30.depth.txt")

        # 2. Stage-specific final BAM targets (Clipped for Modern, Masked for Historical)
        #suffix = ".masked" if src == "historical" else ".clipped"
        stage = "masked" if src == "historical" else "clipped"
        # Stats file (Fixed folder to use underscore _stage instead of dot)
        targets.append(f"results/mapping/{src}/stats/merged_dedup_merged_{stage}/{sid}.{REF_NAME}.merged.dedup.merged.{stage}.stats.txt")
        # BAM file (Fixed path to remove /stats/ folder and added .bam)
        targets.append(f"results/mapping/{src}/{sid}.{REF_NAME}.merged.dedup.merged.{stage}.bam")
        # calculate average depth for final BAMs as well
        targets.append(f"results/mapping/{src}/stats/merged_dedup_merged_{stage}/{sid}.{REF_NAME}.merged.dedup.merged.{stage}.regfilt.Q20.q30.depth.txt")

        #3. MAPDAMAGE TARGETS (Historical Only) 
        if  src == "historical":
            # mapDamage run 1: Before masking run for both historical and modern to allow comparison (but only historical will have the stats file since modern won't be run through mapDamage)
            targets.append(f"results/mapping/{src}/stats/merged_dedup_merged/mapdamage/{sid}.{REF_NAME}")
            # mapDamage run 2: After masking
            #targets.append(f"results/mapping/historical/stats/merged_dedup_merged_masked/mapdamage/{sid}.{REF_NAME}")

    # 4. MultiQC targets for Dedup and final BAMS
    for src in samples_df['source'].unique():
        stage = "masked" if src == "historical" else "clipped"
        targets.append(f"results/mapping/{src}/stats/merged_dedup_merged/multiqc_{src}_dedup_merged_report.html")
        # Fixed to use _{stage} to prevent the {suffix} variable leakage
        targets.append(f"results/mapping/{src}/stats/merged_dedup_merged_{stage}/multiqc_{src}_{stage}_report.html")

    # 5. Add subsampled BAM targets for each sample and stage, if any
    subsample_samples = config.get("subsample_samples", [])
    MAPQ = config["mapQ"]
    target_dp = config.get("subsample_depth", 15) # Fetch the depth
    if subsample_samples:
        for sid in subsample_samples:
            # Find the source (modern/historical) for this specific sample
            src = samples_df[samples_df['sample_id'] == sid]['source'].iloc[0]
            stage = "masked" if src == "historical" else "clipped"
            
            # Request the subsampled deduplicated BAM depth file to trigger the calculate_subs_depth_dedup rule
            targets.append(f"results/mapping/{src}/stats/merged_dedup_merged/subsampled/{sid}.{REF_NAME}.merged.dedup.merged.subs{target_dp}.q{MAPQ}.regfilt.Q20.q30.depth.txt")
            # Request the subsampled final stage BAM depth file to trigger the calculate_subs_depth_dedup rule for the final BAMs
            targets.append(f"results/mapping/{src}/stats/merged_dedup_merged_{stage}/subsampled/{sid}.{REF_NAME}.merged.dedup.merged.{stage}.subs{target_dp}.q{MAPQ}.regfilt.Q20.q30.depth.txt")
    
    # 6. Add Genotyping Targets if enabled in config
    if config.get("run_genotyping", False):
        MIN_DP = config["params"]["run_genotyping"]["minDP"]
        MAX_DP = config["params"]["run_genotyping"]["maxDP"]
        BASEQ = config["baseQ"]
        MAPQ = config["mapQ"]
        
        MISSING_VALS = config["params"]["run_genotyping"].get("maxMissing", [0.0])
        if not isinstance(MISSING_VALS, list):
            MISSING_VALS = [MISSING_VALS]
            
        SITE_TYPES = ["allsites", "biallelic"]
        # Include both 'indCall' and 'jointCall' so Snakemake executes both workflows!
        CALL_TYPES = ["indCall", "jointCall"] 
        
        for m_val in MISSING_VALS:
            for s_type in SITE_TYPES:
                for c_type in CALL_TYPES:
                    # Request the .vcf.gz format to trigger the final bcf2vcf rule
                    targets.append(f"results/genotyping/merged.all.{REF_NAME}.sitefilt.bQ{BASEQ}.mq{MAPQ}.snps5.noIndel.Q30.dp{MIN_DP}-{MAX_DP}.AB.{c_type}.{s_type}.fmiss{m_val}.vcf.gz")
                    # Request the stats file to trigger the ref_bias rule
                    targets.append(f"results/genotyping/merged.all.{REF_NAME}.sitefilt.bQ{BASEQ}.mq{MAPQ}.snps5.noIndel.Q30.dp{MIN_DP}-{MAX_DP}.AB.{c_type}.{s_type}.fmiss{m_val}.bcf.stats.ref_bias")

    # 7. Add Genotyping Targets for the NO-TRANSITIONS workflow
    if config.get("run_genotyping_notrans", False):
        MIN_DP = config["params"]["run_genotyping"]["minDP"]
        MAX_DP = config["params"]["run_genotyping"]["maxDP"]
        BASEQ = config["baseQ"]
        MAPQ = config["mapQ"]
        
        MISSING_VALS = config["params"]["run_genotyping"].get("maxMissing", [0.0])
        if not isinstance(MISSING_VALS, list):
            MISSING_VALS = [MISSING_VALS]
            
        SITE_TYPES = ["allsites", "biallelic"]
        CALL_TYPES = ["indCall", "jointCall"] 
        
        for m_val in MISSING_VALS:
            for s_type in SITE_TYPES:
                for c_type in CALL_TYPES:
                    # Notice the addition of '.notrans.' in the requested file path
                    targets.append(f"results/genotyping_notrans/merged.all.{REF_NAME}.sitefilt.bQ{BASEQ}.mq{MAPQ}.snps5.noIndel.Q30.dp{MIN_DP}-{MAX_DP}.AB.{c_type}.notrans.{s_type}.fmiss{m_val}.vcf.gz")
                    targets.append(f"results/genotyping_notrans/merged.all.{REF_NAME}.sitefilt.bQ{BASEQ}.mq{MAPQ}.snps5.noIndel.Q30.dp{MIN_DP}-{MAX_DP}.AB.{c_type}.notrans.{s_type}.fmiss{m_val}.bcf.stats.ref_bias")
    
    return targets


rule all:
    input: get_final_targets



